services:
  minecraft:
    image: itzg/minecraft-server
    container_name: epearl-minecraft
    restart: unless-stopped
    # stdin and tty are required to attach the web console to the docker container
    stdin_open: true
    tty: true
    ports:
      - '25565:25565'
    environment:
      EULA: 'TRUE'
      VERSION: 'LATEST'
      ENABLE_RCON: 'TRUE'
      RCON_PASSWORD: 'super-safe-rcon-password'
      MEMORY: '512M'
      ENABLE_QUERY: 'TRUE'
    volumes:
      - minecraft_data:/data

  nuxt:
    container_name: epearl-nuxt
    image: ghcr.io/dannypas00/e-pearl:latest
    restart: unless-stopped

  nginx:
    container_name: epearl-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  minecraft_data:
