services:
  minecraft:
    image: itzg/minecraft-server
    container_name: epearl-minecraft
    restart: no
    stdin_open: true
    tty: true
    ports:
      - '25565:25565'
      # NOTE: DO NOT expose this port in production. This is only exposed in development for the local application
      - '25575:25575'
    environment:
      EULA: 'TRUE'
      VERSION: 'LATEST'
      ENABLE_RCON: 'TRUE'
      RCON_PASSWORD: 'super-safe-rcon-password'
      MEMORY: '2G'
      ENABLE_QUERY: 'TRUE'
    volumes:
      - ./minecraft-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  nuxt:
    container_name: epearl-nuxt
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    profiles:
      - prod
