name: Deploy to hetzner server
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          set -eux
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ./hetzner_key
          chmod 600 ./hetzner_key
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.ARTIFACT_HOST }} >> ./known_hosts
          
          scp -P 22 -o "UserKnownHostsFile ./known_hosts" -i ./hetzner_key ./docker-compose.deploy.yaml ${{ secrets.ARTIFACT_USERNAME }}@${{ secrets.ARTIFACT_HOST }}:~/e-pearl/docker-compose.yaml
          ssh -P 22 -o "UserKnownHostsFile ./known_hosts" -i ./hetzner_key ${{ secrets.ARTIFACT_USERNAME }}@${{ secrets.ARTIFACT_HOST }} "cd ~/e-pearl && docker compose -f docker-compose.yaml up --build -d"
